clusterName: kind
collectors:
  daemon:
    suffix: agent
    enabled: true
    scrape_configs_file: "config/kubelet_scrape_configs.yaml"
    labels:
      otel-collector-type: daemonset
    targetAllocator:
      enabled: true
      serviceAccount: targetallocator
      image: ghcr.io/open-telemetry/opentelemetry-operator/target-allocator:main
      allocationStrategy: per-node
      prometheusCR:
        enabled: true
        podMonitorSelector: {}
        scrapeInterval: "30s"
        serviceMonitorSelector: {}
    config:
      exporters:
        otlp:
          endpoint: opentelemetry-kube-stack-gateway-collector:4317   
          tls:
            insecure: true
        debug:
          verbosity: detailed
      service:
        pipelines:
          metrics:
            receivers: [prometheus]
            processors: [k8sattributes]
            exporters: [debug,otlp]
          traces: null
          logs:
            receivers: [filelog]
            processors: [k8sattributes]
            exporters: [debug,otlp]
    presets:
      logsCollection:
        enabled: true
      kubeletMetrics:
        enabled: false
      hostMetrics:
        enabled: false
      kubernetesAttributes:
        enabled: true
  cluster:
    suffix: gateway
    enabled: true
    labels:
      otel-collector-type: deployment
    env:
    - name: CLICKHOUSE_USERNAME
      valueFrom:
        secretKeyRef:
          name: ch-auth
          key: username
    - name: CLICKHOUSE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: ch-auth
          key: password
    image:
      repository: otel/opentelemetry-collector-contrib
      tag: 0.123.0
    presets:
      clusterMetrics:
        enabled: false
    config:
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
            http:
              endpoint: 0.0.0.0:4318
      exporters:
        prometheusremotewrite:
          endpoint: "http://thanos-receive-router-thanos-receive-td-1.thanos-operator-system.svc.cluster.local:19291/api/v1/receive"
        clickhouse:
          endpoint: "tcp://ch:9000"
          username: "admin"
          password: "dMvJU8fypUSzxb1K"
          database: "default"
          create_schema: false
          logs_table_name: otel_logs
          timeout: 10s
          sending_queue:
            queue_size: 100
          retry_on_failure:
            enabled: true
            initial_interval: 5s
            max_interval: 30s
            max_elapsed_time: 300s
      service:
        pipelines:
          metrics:
            receivers: [otlp]
            exporters: [prometheusremotewrite,debug]
          traces: null
          logs:
            receivers: [otlp,k8sobjects]
            exporters: [clickhouse]

instrumentation:
  enabled: false
opAMPBridge:
  enabled: false
kubernetesServiceMonitors:
  enabled: true
kubeApiServer:
  enabled: false
kubelet:
  enabled: false
kubeControllerManager:
  enabled: false
kubeDns:
  enabled: false
kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false
kubeStateMetrics:
  enabled: false
nodeExporter:
  enabled: false